---
kind: pipeline
name: Codequality

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php7.4
  commands:
  - php -v
  - composer update
  - composer require phpmd/phpmd phpstan/phpstan
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: phpcs
  image: joomlaprojects/docker-images:php7.4
  commands:
  - vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards
  - vendor/bin/phpcs -p --report=full --extensions=php --standard=ruleset.xml src/

- name: phpmd
  image: joomlaprojects/docker-images:php7.4
  commands:
  - vendor/bin/phpmd src text cleancode
  - vendor/bin/phpmd src text codesize
  - vendor/bin/phpmd src text controversial
  - vendor/bin/phpmd src text design
  - vendor/bin/phpmd src text unusedcode
  failure: ignore

- name: phpstan
  image: joomlaprojects/docker-images:php7.4
  commands:
  - vendor/bin/phpstan analyse src
  failure: ignore

- name: phploc
  image: joomlaprojects/docker-images:php7.4
  commands:
  - phploc src
  failure: ignore

- name: phpcpd
  image: joomlaprojects/docker-images:php7.4
  commands:
  - phpcpd src
  failure: ignore

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 7.2 lowest

platform:
  os: linux
  arch: amd64

steps:
- name: locales
  image: joomlaprojects/docker-images:php7.2
  commands:
  - apt-get update -y && apt-get install -y glibc-source locales-all
  - localedef -c -i fr_FR -f UTF-8 fr_FR.UTF-8
  - localedef -c -i ru_RU -f CP1251 ru_RU.CP1251

- name: composer
  image: joomlaprojects/docker-images:php7.2
  commands:
  - php -v
  - composer update --prefer-stable --prefer-lowest
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php7.2
  commands:
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 7.2

platform:
  os: linux
  arch: amd64

steps:
- name: locales
  image: joomlaprojects/docker-images:php7.2
  commands:
  - apt-get update -y && apt-get install -y glibc-source locales-all
  - localedef -c -i fr_FR -f UTF-8 fr_FR.UTF-8
  - localedef -c -i ru_RU -f CP1251 ru_RU.CP1251

- name: composer
  image: joomlaprojects/docker-images:php7.2
  commands:
  - php -v
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php7.2
  commands:
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 7.3

platform:
  os: linux
  arch: amd64

steps:
- name: locales
  image: joomlaprojects/docker-images:php7.3
  commands:
  - apt-get update -y && apt-get install -y glibc-source locales-all
  - localedef -c -i fr_FR -f UTF-8 fr_FR.UTF-8
  - localedef -c -i ru_RU -f CP1251 ru_RU.CP1251

- name: composer
  image: joomlaprojects/docker-images:php7.3
  commands:
  - php -v
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php7.3
  commands:
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 7.4

platform:
  os: linux
  arch: amd64

steps:
- name: locales
  image: joomlaprojects/docker-images:php7.4
  commands:
  - apt-get update -y && apt-get install -y glibc-source locales-all
  - localedef -c -i fr_FR -f UTF-8 fr_FR.UTF-8
  - localedef -c -i ru_RU -f CP1251 ru_RU.CP1251

- name: composer
  image: joomlaprojects/docker-images:php7.4
  commands:
  - php -v
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php7.4
  commands:
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 8.0

platform:
  os: linux
  arch: amd64

steps:
- name: locales
  image: joomlaprojects/docker-images:php8.0
  commands:
  - apt-get update -y && apt-get install -y glibc-source locales-all
  - localedef -c -i fr_FR -f UTF-8 fr_FR.UTF-8
  - localedef -c -i ru_RU -f CP1251 ru_RU.CP1251

- name: composer
  image: joomlaprojects/docker-images:php8.0
  commands:
  - php -v
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php8.0
  commands:
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 8.1

platform:
  os: linux
  arch: amd64

steps:
- name: locales
  image: joomlaprojects/docker-images:php8.1
  commands:
  - apt-get update -y && apt-get install -y glibc-source locales-all
  - localedef -c -i fr_FR -f UTF-8 fr_FR.UTF-8
  - localedef -c -i ru_RU -f CP1251 ru_RU.CP1251

- name: composer
  image: joomlaprojects/docker-images:php8.1
  commands:
  - php -v
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php8.1
  commands:
  - vendor/bin/phpunit
  failure: ignore

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: signature
hmac: b6ed17a485142300a60c4de9c553c9584e544ee379b05762a8f2950c56ca7406

...
